/* ORDERS */
export const GET_ORDERS = "GET_ORDERS"
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS"
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL"

export const POST_ADD_ORDER = "POST_ADD_ORDER"
export const POST_ADD_ORDER_SUCCESS = "POST_ADD_ORDER_SUCCESS"
export const POST_ADD_ORDER_FAIL = "POST_ADD_ORDER_FAIL"

export const PUT_UPDATE_ORDER = "PUT_UPDATE_ORDER"
export const PUT_UPDATE_ORDER_SUCCESS = "PUT_UPDATE_ORDER_SUCCESS"
export const PUT_UPDATE_ORDER_FAIL = "PUT_UPDATE_ORDER_FAIL"

export const DELETE_ORDER = "DELETE_ORDER"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL"
